my:
  app:
    cob:
      provider: GoDaddy
      expExist: INACTIVE
    host: smtp.gmail.com
    port: 885
#    port: 990
    username: sample
    pasword: ashok
    protocols:
    - SMTP
    - SMTPS
    - SMTP2
    headers:
      modified: true
      version: 3.2A
      content: JSON
         